---
DBInfo:
  baseURL: http://cmslab3.spa.umn.edu/~cros0400/cgi-bin/WagonDB
  inserter: WagonDBInserter
  name: WagonDB
  reader: WagonDBReadUser
  use_database: true
GUIType: Wagon
SerialCheckSafe: true
#TestHandler: {name: Local, remoteip: localhost}
#TestHandler: {name: SSH, username: <username>, hostname: <hostname>, remoteip: <remoteip>}
TestHandler: {name: ZMQ, localip: <localip>, remoteip: 192.168.140.22, username: <username>, serverpath: <serverpath>, serverscript: <serverscript>}
PhysicalTest: []
Test:
- TestClass: gen_resist_test
  TestPath: /home/HGCAL_dev/sw
  TestScript: wagon_rtd.py
  desc_long: Test must be completed before attempting to measure ID resistor
  desc_short: Measure resistance of analog lines
  name: Resistance Measurement
  required: 1
- TestClass: id_resist_test
  TestPath: /home/HGCAL_dev/sw
  TestScript: wagon_rtd.py
  desc_long: Must be completed after the general resistance measurement
  desc_short: Measure resistance of ID resistor
  name: ID Resistor Measurement
  required: 1
- TestClass: IIC_Check
  TestPath: /home/HGCAL_dev/sw
  TestScript: run_iic_check.py
  desc_long: Test must be completed before BERT for wagon wheel configuration
  desc_short: Check I2C read/write along wagon
  name: I2C Read/Write
  required: 1
- TestClass: BERT
  TestPath: /home/HGCAL_dev/sw
  TestScript: run_bert.py
  desc_long: Needs to be completed after I2C check in order to set up wagon wheel
  desc_short: Determine quality of data transmission
  name: Bit Error Rate Test
  required: 1
UsingScanner: true
...
